server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
      api-key: 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